### ISSUE TITLE
Running it locally

### ISSUE THREAD

**Issue by romelamin** [betofleitass/django_point_of_sale#1]
First of all, thank you for this wonderful work.

Do you have video tutorial how to run it locally? I am stuck in 'run it locally' section, so many things are missing also many other issues. 

If you could please provide a short video where it shows how to install and run it locally.

Thank you

**Comment by betofleitass** [comment]
Thank you for your interest in the project and for opening the issue. I apologize for any inconvenience you experienced while trying to run the project locally. I have updated the README file with detailed instructions for installation and running.

Please review the updated README for step-by-step instructions on prerequisites, installation, and running the project. Although a video tutorial is not available, the README should provide the necessary guidance to successfully run the project.

If you encounter any issues or have further questions, please let me know. It would be helpful if you could provide information about your operating system and specify the missing details or specific issues you encountered.

**Comment by abinasxcode** [comment]
Can you help me with product search in sale_add.html  where you linked product name with input form I am trying to apply search  with name and description but unable to share ajax query
