### ISSUE TITLE
Unable identity search input backend product name in sale_add.html

### ISSUE THREAD

**Issue by abinasxcode** [betofleitass/django_point_of_sale#2]
Can  you help me with product search in sale_add.html where you linked product name with input form I am trying to apply search with name and description but unable to share ajax query 

` $('#searchbox_products').select2({
            delay: 250,
            placeholder: 'Search a product',
            minimumInputLength: 1,
            allowClear: true,
            templateResult: template_product_searchbox,
            ajax:{ 
                url: "{% url 'products:get_products' %}",
                type: 'POST',
                data: function (params) {
                var queryParameters = {
                    term: params.term,
                    //excluir_prod_seleccionados: JSON.stringify(venta.traer_ids())
                }
                return queryParameters;
                },
                processResults: function (data) {
                    console.log(data)
                    return {
                        results: data
                    };
                },
            }

`

 where you mentioned product name in jquery.js of  select2 then please update particular file and code. so we can add another query parameter too

**Comment by betofleitass** [comment]
I wanted to follow up on the issue you raised regarding the product search functionality in sales_add.html. Have you been able to resolve the issue on your end?

If the issue has been resolved and you're willing to contribute the solution, would you mind submitting a pull request? Unfortunately, I'm currently tied up with other commitments and won't be able to dedicate time to the project at the moment.

Your contribution would be greatly appreciated.

**Comment by KagemaNjoroge** [comment]
I have been able to reproduce the error. I noticed that this might be as a result of working offline. While working offline, some JavaScript code fails to load from the CDN and thus causing the issue. Please consider having an active connection while using the web app.
@abinasxcode
