### ISSUE TITLE
Clarification on Python naming convention

### ISSUE THREAD

**Issue by KagemaNjoroge** [betofleitass/django_point_of_sale#5]
I have noticed that some function names are named in uppercase which according to my own view does not follow PEP guidelines. I have modified the code but needed to seek clarification on the naming convention used. 
@betofleitass

**Comment by betofleitass** [comment]
Thank you for bringing this to my attention! I appreciate your effort in modifying the code. To ensure consistency with PEP guidelines, please submit a pull request with your suggested changes, and I'll review it promptly. If you have any further questions or need clarification, feel free to ask. I'm here to help!
